# Generated by Django 5.0.3 on 2024-03-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_venta_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='Cliente',
            field=models.CharField(help_text='Por favor, ingresa el nombre y apellido sin espacios entre las palabras.', max_length=120),
        ),
    ]
