# Generated by Django 5.0.3 on 2024-03-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0003_alter_venta_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='Barrio',
            field=models.CharField(help_text='Por favor, ingresa el nombre del barrio sin espacios entre las palabras.', max_length=120),
        ),
    ]
