# Generated by Django 5.0.3 on 2024-03-29 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0004_alter_venta_barrio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='Mes',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
