# Generated by Django 5.0.3 on 2024-03-29 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0005_alter_venta_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='Mes',
            field=models.IntegerField(default=3, error_messages={'max_value': 'El mes debe estar entre 1 a 12.', 'min_value': 'El mes debe estar entre 1 a 12.'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
